train_file: ['data/vqa_train.json',
            'data/vqa_val.json',   
            #  'data/vg_qa.json'
             ]
             
test_file: ['data/vqa_test.json']
answer_list: 'data/answer_list.json'

vqa_root: 'data/' #train2014/
vg_root: 'data/'  #image/

image_res: 224 # 384
batch_size_train: 32 # 32 
batch_size_test: 16 # 16 
k_test: 128 #128

# pretrain model part, to ignore
alpha: 0.
distill: False
warm_up: False

eos: '[SEP]'

bert_config: 'configs/config_bert_small.json'

optimizer: {opt: adamW, lr: 2e-5, weight_decay: 0.02}
schedular: {sched: cosine, lr: 2e-5, epochs: 8, min_lr: 1e-6, decay_rate: 1, warmup_lr: 1e-5, warmup_epochs: 4, cooldown_epochs: 0}







